<?php
    if (basename(__FILE__) === basename($_SERVER['SCRIPT_FILENAME'])) {
        http_response_code(403);
        exit;
    }

    // Now let's create an array of error messages for the error pages to use.
    function getErrorMessage($code) {
        $messages = [
            400 => [
                "That request was more corrupted than a glitched save file.",
                "Bad request... did you try entering a cheat code?",
                "Looks like you clipped through the map.",
                "See that guy over there? Yeah, man. That's a Bad Request.",
                "Your request bugged out harder than Cyberpunk on launch day.",
                "Bad Request... You rolled a nat 1 on your input.",
                "Invalid request packet. Did you forget to equip your keyboard?"
            ],
            401 => [
                "You need to unlock this area first. (Hint: try logging in.)",
                "Unauthorized! You haven't leveled up enough to enter here.",
                "Access denied - You don't have the right keycard.",
                "Unauthorized - This dungeon requires party membership.",
                "You tried to open a locked chest without the proper lockpicking skill.",
                "Authorization Required - This zone is behind a paywall. (Just kidding... or are we?)",
                "Your credentials were as effective as a wooden sword vs. a dragon.",
                "Login failed: Wrong cheat code entered.",
                "This door is locked. Find the red keycard to continue.",
                "Unauthorized: You don't have the Season Pass.",
                "You can't join the lobby without the password.",
                "This class requires authentication before you can play.",
                "Your access attempt was blocked by the DM. Roll again next session.",
                "You must be at least level 20 to enter.",
                "This content is exclusive to premium players.",
                "The system rejected you harder than Dark Souls rejects casuals.",
                "This raid is invite-only.",
                "Error: Controller not connected.",
                "Your login attempt got crit-failed.",
                "You need to equip the correct credentials to proceed."
            ],
            403 => [
                "I used to be an adventurer like you... Until I found a forbidden page.",
                "Forbidden! You don't have the quest item required to enter.",
                "Access denied - this dungeon requires a guild membership.",
                "You Shall Not Pass!",
                "Welcome to 403: Forbidden Resource - The server understood the request but refuses to authorize it.",
                "Forbidden City - You don't have permission to access this area.",
                "Can't let you in, Jim!",
                "You are not allowed to enter here.",
                "You... You can't do that!",
                "Insufficient permissions.",
                "You don't have access to this. Go watch a YouTube video about it.",
                "Intruder alert!",
                "No trespassing!",
                "You lost The Game.",
                "You haven't unlocked this part of the map yet.",
                "You cannot cross the world border.",
                "Access denied. This zone requires the Season Pass DLC.",
                "Locked! You need a higher lockpicking skill to open this.",
                "403: You must be this tall to ride.",
                "VIP-only area. Better grind that rep first.",
                "This door is barred from the other side.",
                "Sorry, this raid is invite-only.",
                "You tried to glitch through the wall... and got caught.",
                "The bouncer stopped you at the door. (Better get on the list.)",
                "The devs didn't want you here.",
                "Forbidden! Page flagged as 'cheater'.",
                "Hidden behind fog of war."
            ],
            404 => [
                "Looks like this page is missing... maybe it went AFK.",
                "The page rolled a natural 1 on its stealth check.",
                "This page doesn't exist... maybe it rage-quit.",
                "Quest marker not found. Try checking your map again.",
                "Page failed its perception check.",
                "The loot you were looking for isn't here... Try another dungeon.",
                "That page was deleted faster than a noob in Dark Souls.",
                "This is the wrong warp.",
                "This page doesn't exist. It must have been Thanos-snapped from existence.",
                "Oops... looks like the NPC that gives this quest never spawned.",
                "I don't know how you got here, but it's time to leave.",
                "Peek a boo!",
                "Congrats. You broke it. I'm as shocked as you are — but don't worry, there's an easy fix. <a href=\"javascript:location.reload()\" class=\"cta-button\">[CLICK HERE]</a>",
                "Thank you Mario! But our princess is in another castle!",
                "I think this page got lost on the way to use the restroom.",
                "You've reached the world border. Turn back.",
                "Game.exe not found. You may need to reinstall the game.",
                "You lost The Game.",
                "An error occured while updating Frostbyt3Gaming (missing file privileges) : C:\Program Files (x86)\Steam\steamapps\common\Frostbyt3Gaming",
                "Host left the game.",
                "Frostbyt3Gaming has left the chat.",
                "Easter Egg Not Found",
                "We can't seem to find this page. Maybe try again?",
                "Mash F5 and hope it fixes this issue.",
                "Achievement Unlocked! You found the 404 page.",
                "Quest Failed: Page not found.",
                "Loot box empty. Better luck next refresh.",
                "Secret level locked. (Hint: This isn't it.)",
                "Debug message: You weren't supposed to see this.",
                "Respawn failed. Page could not be located.",
                "The map didn't load. Please try another server.",
                "This instance is full. Try re-queueing.",
                "This page fell through the world. (Classic bug.)",
                "Quest not available in this region.",
                "Fast travel failed. Destination doesn't exist.",
                "Page skipped leg day and couldn't load.",
                "This area is still under construction. Come back after the next patch.",
                "Out of memory. Please insert another RAM stick.",
                "The server rolled back and erased this page.",
                "Critical mission objective missing. Restart required.",
                "Page vanished like your favorite MMO after launch hype.",
                "This dungeon requires the DLC.",
                "Page despawned due to inactivity.",
                "Page KO'd. Better luck next round.",
                "The page got stuck in a tree texture and never came back.",
                "MissingNo. has appeared.",
                "This page was banned for exploiting glitches.",
                "Not Found - but hey, at least it's not a blue shell.",
                "The page wandered into the fog of war.",
                "The page lagged out during the cutscene.",
                "Page got bodied by the tutorial boss.",
                "Controller disconnected.",
                "Checkpoint not found. You'll have to start over.",
                "The page aggro'd the wrong boss and got one-shotted.",
                "This page rage-quit to desktop.",
                "Page fell victim to friendly fire.",
                "The page went AFK and got kicked from the server.",
                "This page failed its save throw against deletion.",
                "Page wiped with the raid group. Better luck next run",
                "The page glitched through the floor and kept falling.",
                "Page corrupted. Please blow on the cartridge.",
                "This page was nerfed out of existence in the last patch.",
                "Page tried to quicksave in combat. It didn't end well."
            ],
            420 => [
                "Hah! I see what you did there.",
                "When you smoke the herb, it reveals you to yourself.",
                "Happy 420!",
                "Stop killing each other, man! Let's just smoke a blunt.",
                "Couples who blaze together, stay together.",
                "It's 420 somewhere.",
                "I find it quite ironic that the most dangerous thing about weed is getting caught with it.",
                "It's called CANnabis, not CAN'Tabis.",
                "I don't think pot is more dangerous than alcohol.",
                "Can't complain when you've got Mary Jane.",
                "That is not a drug, it's a leaf.",
                "The biggest killer on the planet is stress, and I think the best medicine is and always has been cannabis.",
                "Sativa to change the things I can, indica to accept the things I can't.",
                "Struggle is the enemy, but weed is the remedy.",
                "Never give up the ganja.",
                "Make the most you can of the Indian hemp seed and sow it everywhere. - George Washington",
                "If you ever miss 4:20, just wait until 4:22. Because 4:22 is 4:20, too.",
                "I got high, and forgot I wasn't supposed to get high.",
                "If we all had a bong, we'd all get along!",
                "Is marijuana addictive? Yes, in the sense that most of the really pleasant things in life are worth endlessly repeating.",
                "Don't worry. Don't cry. Smoke weed and get high.",
                "Why is marijuana against the law? It grows naturally upon our planet. Doesn't the idea of making nature against the law seem a bit... unnatural?",
                "People say you can abuse marijuana. Well, you can abuse cheeseburgers too, you know? You don' go around closing Burger King because you can abuse something.",
                "A friend with weed is a friend indeed. A friend who shares is a friend who cares.",
                "Sometimes you gotta say \"fuck it\" and smoke a big ass joint.",
                "A marijuana high can enhance core human mental abilities.",
                "Don't judge someone until you have shared a joint with them.",
                "It's hard to be mean when you're stoned.",
                "You either love weed, or you're wrong.",
                "Smoke the marijuana and get high. Stay above the wicked and fly.",
                "Weed is from the earth. God put this here for me and you. Take advantage, man, take advantage.",
                "Don't kill my high because you're low.",
                "Kush rolled, glass full. I prefer the finer things.",
                "I was gonna clean my room... Until I got high. (ooh)",
                "I was gonna get up and find the broom, but then I got high. (la-la-ta, ta-ta-ra-ra)",
                "My room is still messed up, and I know why! (Why, man?)",
                "'Cause I got high, because I got high, because I got high. (la-la-ta, ta-ta-ra-ra)",
                "Colt 45 and two Zig-Zags, baby, that's all we need!",
                "Stop and hit the bong like Cheech & Chong, and sell tapes from here to Hong Kong.",
                "Whatever I do, I do it better stoned.",
                "I think America's view on weed is ridiculous. If everyone smoked weed, the world would be a better place.",
                "Smoking weed doesn't make you cool, but if you're cool then you probably smoke weed.",
                "Even if one doesn't smoke weed, one has to see the benefits of decriminalizing it!"
            ],
            500 => [
                "The server has encountered a fatal error... press F to pay respects.",
                "The server blue-screened harder than a PS2.",
                "Oops! The server cast self-destruct.",
                "Critical hit! The server took massive damage.",
                "Our backend just rage-quit mid-match.",
                "The server tried to roll initiative... and died.",
                "Someone pulled the wrong lever in the control room.",
                "The server encountered an error more confusing than Dark Souls lore.",
                "This crash was super effective.",
                "Game over, man! Game over! (But we'll be back soon.)"
            ],
            502 => [
                "Connection failed. The gateway is as unstable as a DayZ server.",
                "The server got stuck in a loading zone.",
                "The servers had a miscommunication. (Probably arguing over loot.)",
                "Party chat disconnected. Try reconnecting.",
                "The server link cable got unplugged.",
                "Looks like the NPC didn't understand your dialogue option.",
                "Our servers had trouble talking to each other. Awkward silence ensued.",
                "The guild leader forgot to send the invite.",
                "The connection was dropped faster than a noob in Ranked.",
                "The gateway is more broken than Cyberpunk's AI at launch.",
                "Someone forgot to forward the port."
            ],
            503 => [
                "Server is on cooldown. Please wait before trying again.",
                "The healer went AFK.",
                "Our server is resting at the inn. Try again later.",
                "The raid group wiped. Give us a sec to respawn.",
                "The server is patching. (Nerfs incoming, sorry.)",
                "This service is temporarily unavailable due to lack of discipline.",
                "The server queue is full. Please mash F5 repeatedly.",
                "The boss pulled the plug mid-fight.",
                "The server is in maintenance mode. Grab a snack, we'll be back.",
                "Too many players connected at once. (It's basically launch day.)"
            ],
            504 => [
                "The server took too long... must be stuck in a loading screen.",
                "Hold up... The server took way too long to respond. Try again in a bit.",
                "Lag monster strikes again.",
                "This request timed out harder than dial-up internet.",
                "The server froze like Skyrim without patches.",
                "The backend went AFK mid-response.",
                "That took longer than waiting for a WoW raid queue.",
                "Timeout! The server clearly didn't invest in stamina upgrades.",
                "Connection lost. Reconnecting... nevermind.",
                "The server response time is higher than your ping in Australia"
            ],
            "defaulted" => [
                "An unknown error has occurred. Someone probably aggro'd the server boss.",
                "Welp. I don't know what to do here.",
                "What else did you expect?",
                "$#&%... Something broke.",
                "Looks like you've gone off script.",
                "Well, this is awkward...",
                "Congratulations, you found the MissingNo of error codes.",
                "Plot twist not found in script.",
                "This isn't a bug, it's a surprise feature!",
                "Unknown error. Roll a d20 to continue.",
                "Press any key to continue...",
                "You broke reality. Hope you're proud.",
                "Achievement unlocked: Triggered an undefined error.",
                "404... wait, no, that's not it either.",
                "This is fine. *Everything is on fire.*",
                "Unknown error. Insert coin to try again.",
                "Even the error handler threw an error. GG.",
                "You clipped out of bounds in the error system.",
                "Oops, you've reached cut content.",
                "The server just used a cheat code on itself.",
                "Undefined error: The devs didn't think you'd get here.",
                "No lollygaggin'",
                "Do you get to the cloud district very often? Oh, what am I saying, of course you don't.",
                "You see those warriors from Hammerfell? They've got curved swords. Curved. Swords.",
                "We know",
                "Let me guess - someone stole your sweetroll.",
                "You never should've come here!"
            ]
        ];

        if (isset($messages[$code])) {
            $lines = $messages[$code];
            return $lines[array_rand($lines)]; // pick one at random
        }
        
        // Default fallback
        if (isset($messages['defaulted'])) {
            $defaultlines = $messages['defaulted'];
            return $defaultlines[array_rand($defaultlines)];
        }

        // Final safety net (in case defaulted ever gets deleted)
        return "An unknown error has occurred. Someone probably aggro'd the server boss.";
    }
?>